name: Label Added Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  check_label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          pagerduty:
            - 'pagerduty/schedule.tf'
            
    - name: Check if specific label added
      if: ${{ github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'automerge') }}
      uses: andymckay/labeler@master    
      with:
        remove-labels: "automerge"
