name: Label Added Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  check_label:
    runs-on: ubuntu-latest

    steps:  
    - name: Check if specific label added
      if: ${{ github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'automerge') }}
      uses: CoinFlip/main/.github/workflows/pagerduty_shcedule_check.yaml@main
