name: Check PagerDuty Schedule Update

on:
  pull_request:
    paths:
      - 'pagerduty/schedule.tf'

jobs:
  check-schedule-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in pagerduty/schedule.tf
        id: check-changes
        run: |
         git fetch --unshallow
          if git diff --name-only origin/${{ github.base_ref }} HEAD | grep 'pagerduty/schedule.tf'; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Comment on PR if pagerduty/schedule.tf is modified
        if: steps.check-changes.outputs.changes == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            comment = `
            Changes detected in 'pagerduty/schedule.tf'. Please ensure to update the 'rotation_virtual_start' parameter as described in the instructions [here](https://github.com/Himanshukaushik303/atlan#how-to-run).`;
            github.pulls.createReviewComment({...context.repo, pull_number: context.issue.number, body: comment});
