name: CheckModifiedFile

on:
  pull_request

jobs:
  check_modifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine file changes
        id: file_changes
        run: |
          if git diff --name-only origin/${{ github.base_ref }} HEAD | grep 'pagerduty/schedule.tf' ; then
          echo "modified=true" >> $GITHUB_OUTPUT
          else
          echo "modified=false" >> $GITHUB_OUTPUT
          fi
          echo "$modified"
          
      - name: Echo Storybook build link
        uses: actions/github-script@v6
        if: ${{steps.file_changes.outputs.modified}}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'It seems like there are changes to "pagerduty/schedule.tf".\n' + 'Please make sure to update the "rotation_virtual_start" parameter as described in the instructions [here](https://github.com/Sanyaku/sumo-content-management/blob/master/pagerduty/README.md#instructions-for-fixing-schedules-after-an-employee-departure).' 
            })
