name: Check_ModifiedFile

on:
  pull_request:
    paths:
      - 'pagerduty/schedule.tf'

jobs:
  check_modifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'It seems like there are changes to "pagerduty/schedule.tf".\n' + 'Please make sure to update the "rotation_virtual_start" parameter as described in the instructions [here](https://github.com/Sanyaku/sumo-content-management/blob/master/pagerduty/README.md#instructions-for-fixing-schedules-after-an-employee-departure).' 
            })
            
      - name: Remove label from PR
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'automerge'
              });
            } catch (err) {
              if (err.status === 404 && err.message === "Label does not exist") {
                console.log("Label not found");
              } else {
                throw err;
              }
            }
