name: Check PagerDuty Schedule Update

on: pull_request
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          pagerduty:
            - 'pagerduty/schedule.tf'
            
    - name: Comment PR
      if: steps.filter.outputs.pagerduty == 'true'
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          It seems like there are changes to 'pagerduty/schedule.tf'. Please make sure to update the 'rotation_virtual_start' parameter as described in the instructions [here](https://github.com/Himanshukaushik303/CoinFlip/blob/main/README.md#transactions).`;
    
    - name: label remover
      uses: andymckay/labeler@master
      with:
        remove-labels: "automerge"
