name: Check PagerDuty Schedule Update

on: pull_request
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          pagerduty:
            - 'pagerduty/schedule.tf'
            
    - name: Comment PR
      if: steps.filter.outputs.pagerduty == 'true'
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Hello world ! :wave:
